package:
  name: q2-mfa
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  build:
    - python {{ python }}
    - pip
    - setuptools
    - versioningit

  run:
    - pandas
    - prince-factor-analysis
    - scikit-bio
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}

test:
  requires:
    - parameterized
  commands:
    - pytest --pyargs q2_mfa

about:
  home: https://github.com/bokulich-lab/q2-q2_mfa
  license: BSD-3-Clause
  license_family: BSD
